### ISSUE TITLE
acces to repository

### ISSUE THREAD

**Issue by Fruchtgummi** [bitnami/bitnami-docker-harbor-portal#12]
This composing works on a AWS EC2 instance. The logs are without attracting attention.

If I push the repo to harbor, shows follow error:

```
The push refers to repository [registry.mydomain.com/my/app]
3cfc00ea5929: Pushing [==================================================>]  29.58MB/29.58MB
497f07ba5b49: Pushing [==================================================>]  332.7MB/332.7MB
ab392566db20: Pushing  2.048kB
4d4771a7059c: Pushing [==================================================>]  552.5kB/552.5kB
6b27de954cca: Preparing
unauthorized: unauthorized to access repository: my/app, action: push: unauthorized to access repository: my/app, action: push

```

The instance have a aws classic load-balancer and the port 80 and 443 is open to the world.

**Comment by marcosbc** [comment]
Does it work without the load balancer? I see a similar issue reported here: https://github.com/goharbor/harbor/issues/12229

So maybe this is more of an upstream issue rather than specific to Bitnami's chart.

**Comment by Fruchtgummi** [comment]
The problem is the header forward...

Resolve with:

`sed -i 's/proxy_set_header X-Forwarded-Proto $scheme;/#proxy_set_header X-Forwarded-Proto $scheme;/g' config/proxy/nginx.conf`

**Comment by marcosbc** [comment]
Thanks for sharing. Note that it is the default configuration for the upstream Harbor docker-compose, which we're basing on: https://github.com/goharbor/harbor/blob/master/make/photon/prepare/templates/nginx/nginx.http.conf.jinja#L75

In your case, it looks like it must be commented like you mention:

```nginx
# When setting up Harbor behind other proxy, such as an Nginx instance, remove the below line if the proxy already has similar settings.
proxy_set_header X-Forwarded-Proto $scheme;
```

So I understand this is solved. Unfortunately there's not much we can do about it for now, so I'll proceed to close this issue..
