### ISSUE TITLE
CSRF

### ISSUE THREAD

**Issue by Fruchtgummi** [bitnami/bitnami-docker-harbor-portal#14]
Error:

/server/middleware/csrf/csrf.go:57]: Invalid CSRF key from environment: , generating random key...

**Comment by dani8art** [comment]
Hi @Fruchtgummi, thank you fo opening the issue, please could you share with us a bit more info?

How are you deploying this container? which configuration are you using? and some other info that can help us to reproduce it in our environment.

**Comment by Fruchtgummi** [comment]
https://github.com/goharbor/harbor/issues/13169#issue-709559020

**Comment by dani8art** [comment]
So It seems you already resolved this issue, right?
