### ISSUE TITLE
Clean up?

### ISSUE THREAD

**Issue by Fruchtgummi** [bitnami/bitnami-docker-harbor-portal#16]
How a cleanup old images on Harbor? If I deleted the images on Adminpanel, this has no effect on the memory. How do I free up disk space?

**Comment by FraPazGal** [comment]
Hello @Fruchtgummi,

Thanks for opening this issue! Per [harbor documentation](https://goharbor.io/docs/2.0.0/working-with-projects/working-with-images/pulling-pushing-images/#deleting-repositories), removing an image using the Harbor interface will only soft delete it. You probably need to also delete the repository files by running `garbage collection`.
