### ISSUE TITLE
harbor-core dies because of `nil pointer dereference` during proxy pull

### ISSUE THREAD

**Issue by FrodoBeuthling** [bitnami/bitnami-docker-harbor-portal#18]
**Description**

While using Harbor as proxy for e.g. Docker Hub pulls fail and the harbor-core container dies.

I put this issue here because the "solution" is related to this repos `docker-compose.yml`.

**Steps to reproduce the issue:**

1. take the `docker-compose.yml` of this repo
2. update the labels for the harbor containers to explicitly use version 2.2.2  
   (because at least for harbor-core a version 2.3.0 image is not available yet and at least harbor-jobservice 2.3.0 and harbor-core 2.2.2 are not compatible)
3. run `docker-compose up -d`
4. create a registry and project to proxy Docker Hub
5. try to pull an image via the newly created project

**Describe the results you received:**

The pull results in an error:
```shell
$ docker pull harbor/test/library/python
Using default tag: latest
latest: Pulling from test/library/python
received unexpected HTTP status: 502 Bad Gateway
```

The harbor-core container dies and restarts with the following error message:
```log
2021-06-24T14:32:45Z [WARNING] [/server/middleware/repoproxy/proxy.go:139]: Artifact: test/library/python:, digest:sha256:0b805244ce34d29913b1a1bdd41692c240d159bf81be0a989f1408d452d03f4a is not found in proxy cache, fetch it from remote repo
2021-06-24T14:32:45Z [DEBUG] [/server/middleware/repoproxy/proxy.go:141]: the tag is , digest is sha256:0b805244ce34d29913b1a1bdd41692c240d159bf81be0a989f1408d452d03f4a
2021-06-24T14:32:45Z [DEBUG] [/controller/proxy/manifestcache.go:71]: cache manifest list with key=cache:manifestlist:test/library/python:sha256:0b805244ce34d29913b1a1bdd41692c240d159bf81be0a989f1408d452d03f4a
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1c0e6d0]

goroutine 904 [running]:
github.com/goharbor/harbor/src/controller/proxy.(*ManifestListCache).CacheContent(0xc000954240, 0x26e6e80, 0xc000f23860, 0xc00096bc15, 0xe, 0x26ae520, 0xc001728ff0, 0xc00096bc08, 0x1b, 0xc00096bc2e, ...)
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/manifestcache.go:72 +0x230
github.com/goharbor/harbor/src/controller/proxy.(*controller).waitAndPushManifest(0xc000b5ae60, 0x26e6e80, 0xc000f23860, 0xc00096bc15, 0xe, 0x26ae520, 0xc001728ff0, 0xc00096bc08, 0x1b, 0xc00096bc2e, ...)
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/controller.go:278 +0x11e
github.com/goharbor/harbor/src/controller/proxy.(*controller).ProxyManifest.func2(0xc000b5ae60, 0xc00096bc08, 0x1b, 0xc00096bc2e, 0x47, 0xc00096bc08, 0xc, 0xc00096bc2e, 0x47, 0x0, ...)
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/controller.go:213 +0x245
created by github.com/goharbor/harbor/src/controller/proxy.(*controller).ProxyManifest
        /bitnami/blacksmith-sandox/harbor-core-2.2.2/src/github.com/goharbor/harbor/src/controller/proxy/controller.go:201 +0x4e8
```

**Describe the results you expected:**

The pull scceeds:
```shell
$ docker pull harbor/test/library/python
Using default tag: latest
latest: Pulling from test/library/python
0bc3020d05f1: Pull complete
a110e5871660: Pull complete
83d3c0fa203a: Pull complete
a8fd09c11b02: Pull complete
14feb89c4a52: Pull complete
70752631d778: Pull complete
b4cfcef19326: Pull complete
b51fbcb03c35: Pull complete
b11f09273b0c: Pull complete
Digest: sha256:0b805244ce34d29913b1a1bdd41692c240d159bf81be0a989f1408d452d03f4a
Status: Downloaded newer image for harbor/test/library/python:latest
harbor/test/library/python:latest
```

**Additional information you deem important (e.g. issue happens only occasionally):**

src/controller/proxy/manifestcache.go:72 relies on the default cache being initialized which does not happen if the environment variable `_REDIS_URL_CORE` is not set.

Setting `_REDIS_URL_CORE` to a valid redis address "fixes" the issue.

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.14.2
 Git commit:        42e35e61f352
 Built:             Tue Jun  2 12:00:00 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.11
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.14.2
  Git commit:       42e35e61f352
  Built:            Tue Jun  2 12:00:00 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.1.3_catatonit
  GitCommit:

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 78
  Running: 70
  Paused: 0
  Stopped: 8
 Images: 67
 Server Version: 19.03.11
 Storage Driver: btrfs
  Build Version: Btrfs v4.15
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: oci runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version:
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.3.18-24.37-default
 Operating System: SUSE Linux Enterprise Server 15 SP2
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 62.46GiB
 Name: lpdocker06
 ID: GHDP:7YXB:XPQD:2PXC:BLYT:O6KF:YULZ:XDO7:QDSD:PCZL:PLB6:EG5F
 Docker Root Dir: /global/docker/.docker
 Debug Mode: false
 HTTP Proxy: [...]
 HTTPS Proxy: [...]
 No Proxy: [...]
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
docker-py version: 3.6.0
CPython version: 3.6.7
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by alvneiayu** [comment]
hi @FrodoBeuthling 

I can not reproduce the problem, I think that I am missing something. Could you share with me your docker-compose, please?

Thanks a lot for your time

Álvaro

**Comment by FrodoBeuthling** [comment]
Hi @alvneiayu,

thanks for having a look at it. I'll attach two `docker-compose` a working and a non working one.
[docker-compose_doesnt_work.yml.txt](https://github.com/bitnami/bitnami-docker-harbor-portal/files/6716554/docker-compose_doesnt_work.yml.txt)
[docker-compose_works.yml.txt](https://github.com/bitnami/bitnami-docker-harbor-portal/files/6716560/docker-compose_works.yml.txt)

Our Harbor sits behind an outbound proxy, i would not have expected that to have an influence on the situation but i left it in the compose just in case it does.

I'll also attach screenshots of the registry and project configuration, maybe it helps.
![new_registry_endpoint](https://user-images.githubusercontent.com/8430243/123435451-df855000-d5cd-11eb-8cf8-cabea80e6043.PNG)
![new_project](https://user-images.githubusercontent.com/8430243/123435467-e318d700-d5cd-11eb-8add-5ee134d185d1.PNG)

**Comment by alvneiayu** [comment]
hi @FrodoBeuthling 

Thanks for sharing the docker-compose. Let me try to investigate a little bit. I will come back with some feedback.

Thanks a lot

Álvaro

**Comment by stonezdj** [comment]
The environment `_REDIS_URL_CORE` is required to initialize the cache. if missing, then the cache is nil

**Comment by alvneiayu** [comment]
hi @FrodoBeuthling 

Did you test with the solution proposed by @stonezdj?

Thanks a lot

Álvaro

**Comment by FrodoBeuthling** [comment]
Hi @alvneiayu,

sorry for not responding, i forgot about this.
Yes, as seen in the `docker-compose_works.yml.txt` what @stonezdj proposed was what i did to get it working.

Thanks
