### ISSUE TITLE
bitnami/bitnami-docker-harbor-portal not support proxy cache settings ?

### ISSUE THREAD

**Issue by srcgrp** [bitnami/bitnami-docker-harbor-portal#22]
### Name and Version

 bitnami/bitnami-docker-harbor-portal:2

### What steps will reproduce the bug?

1- Use bitnami/bitnami-docker-harbor-portal docker-compose.yml
2- In Harbor web UI, create a "registry" with provider "Docker Hub" and endpoint URL "https://hubs.docker.com/"
3- In "Projects" page, click "New Project" button
4- Fill in a "Project name", enable "proxy cache" and select the source we fill in in step 1. and click "OK"
5- Server replies "bad request: unsupported registry type docker-hub"

### What is the expected behavior?

Should be able to save the setting.

### What do you see instead?

when request POST to `/api/v2.0/projects` with this payload `{"project_name":"i","metadata":{"public":"false"},"storage_limit":-1,"registry_id":3}` response will provide below error:

`{"errors":[{"code":"BAD_REQUEST","message":"bad request: unsupported registry type docker-hub"}]}`

I attempt with various version of bitnami/harbor-core:2.4* and error it was still there.

**Comment by javsalgar** [comment]
Hi,

It is not clear to me if this is an issue with the Bitnami configuration or an upstream harbor issue. Did the same issue happen with the upstream harbor containers?
