### ISSUE TITLE
[bitnami/harbor] swagger.json missing

### ISSUE THREAD

**Issue by schnatterer** [bitnami/bitnami-docker-harbor-portal#3]
**Which chart**:
harbor

**Describe the bug**
Swagger.json missing

**To Reproduce**

1. Start the bitnami/harbor helm chart 
2. go to `<harbor-url>/devcenter`
3. the page is empty
4. when GETing the `<harbor-url>/swagger.json` directly it returns 200 but shows 404
5. when looking in the image there is no swagger.json  
    `docker run --rm -it --entrypoint ls bitnami/harbor-portal:1.10.2-debian-10-r29`
6. when looking in the official image, there is a swagger.json
   `docker run --rm -it --entrypoint ls  goharbor/harbor-portal:v1.10.2 /usr/share/nginx/html/`

**Expected behavior**
the swagger ui is showing

**Additional context**

Workaround: Use the official portal image
```yaml
portalImage:
  repository: goharbor/harbor-portal
  tag: v1.10.2 
```

**Comment by andresbono** [comment]
Hi @schnatterer, I have transferred this issue to https://github.com/bitnami/bitnami-docker-harbor-portal.

It seems swagger-ui is configured here: https://github.com/goharbor/harbor/blob/119751e0fdd930d02e0bf354ba0e6198ff37c2d8/src/portal/package.json#L7

However, for the `v1.10.2` tag, that `postInstall` script is not included: https://github.com/goharbor/harbor/blob/v1.10.2/src/portal/package.json

We will be checking possible solutions for this.

**Comment by schnatterer** [comment]
@andresbono Thanks!

Don't know if that helps but the official harbor 1.10.2 image seems to include the `swagger.json`

```
docker run --rm -it --entrypoint ls  goharbor/harbor-portal:v1.10.2 -l /usr/share/nginx/html/ | grep swagger
```

**Comment by andresbono** [comment]
Thanks for pointing it out.

**Comment by juan131** [comment]
Hi everyone,

Could you please give a try to the new major version (`6.0.0`) that includes the new major version of Harbor `2.0.0`? This issue was addressed on that major version.

**Comment by schnatterer** [comment]
Just installed a fresh `bitnami/harbor` release (chart version 6.0.2).
Still no swagger.json.
But I found #5  :stuck_out_tongue:

**Comment by javsalgar** [comment]
Hi,

Just a note to let you know that the release below has the issue solved. Now the swagger UI is available

 https://github.com/bitnami/bitnami-docker-harbor-portal/commit/5a48ad72be73b4c1930ae54fa4a93bee1b8338ed

**Comment by schnatterer** [comment]
Thanks @javsalgar 
I can see `swagger.jsons` in `docker.io/bitnami/harbor-portal:2.0.0-debian-10-r13`. So presumably, this will work in harbor.
Thanks!
