### ISSUE TITLE
docker login doesn't work

### ISSUE THREAD

**Issue by siredmar** [bitnami/bitnami-docker-harbor-portal#4]
please see https://github.com/goharbor/harbor/issues/12271

**Comment by juan131** [comment]
Hi @siredmar 

You mentioned:

> The only thing changed in the docker-compose.yml is EXT_ENDPOINT=http://harbor.lan for core service.

So I guess you have applied this change:

```
diff --git a/docker-compose.yml b/docker-compose.yml
index 9f26800..1250ad6 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -40,7 +40,7 @@ services:
       - _REDIS_URL_REG=redis://redis:6379/1
       - PORT=8080
       - LOG_LEVEL=info
-      - EXT_ENDPOINT=http://reg.mydomain.com
+      - EXT_ENDPOINT=http://harbor.lan
       - DATABASE_TYPE=postgresql
       - REGISTRY_CONTROLLER_URL=http://registryctl:8080
       - POSTGRESQL_HOST=postgresql
```

Please note that, in that case, you also need to adapt the registry `config.yml`, see: https://github.com/bitnami/bitnami-docker-harbor-portal/blob/master/config/registry/config.yml#L28

**Comment by siredmar** [comment]
> Hi @siredmar
> 
> You mentioned:
> 
> > The only thing changed in the docker-compose.yml is EXT_ENDPOINT=http://harbor.lan for core service.
> 
> So I guess you have applied this change:
> 
> ```
> diff --git a/docker-compose.yml b/docker-compose.yml
> index 9f26800..1250ad6 100644
> --- a/docker-compose.yml
> +++ b/docker-compose.yml
> @@ -40,7 +40,7 @@ services:
>        - _REDIS_URL_REG=redis://redis:6379/1
>        - PORT=8080
>        - LOG_LEVEL=info
> -      - EXT_ENDPOINT=http://reg.mydomain.com
> +      - EXT_ENDPOINT=http://harbor.lan
>        - DATABASE_TYPE=postgresql
>        - REGISTRY_CONTROLLER_URL=http://registryctl:8080
>        - POSTGRESQL_HOST=postgresql
> ```
> 
> Please note that, in that case, you also need to adapt the registry `config.yml`, see: https://github.com/bitnami/bitnami-docker-harbor-portal/blob/master/config/registry/config.yml#L28

sorry, i didn't mention this file. I did change the registry/config.yaml
```
    realm: http://harbor.lan/service/token
```

**Comment by juan131** [comment]
Sorry for the late response @siredmar 

Could you please provide the steps you followed to create the repository through the Harbor Admin portal? Please be as descriptive as possible.

Could you also attach a screenshot of the "repositories" view in Harbor portal?

**Comment by shrisidepocket** [comment]
Bumping this, same issue with similar configs. @juan131 what do you mean by create a repository through the portal? I see we can create projects, and then the docker push creates the repo under the project?

**Comment by juan131** [comment]
Hi everyone,

I am struggling with connecting via `localhost` (or `127.0.0.1`) too. Even if I associate it to the domain `reg
.mydomain.com` in the `/etc/hosts` file:

```console
$ cat /etc/hosts
(...)
127.0.0.1       reg.mydomain.com
```

I'm not 100% sure about what's going, but I'd say sth in the Docker client is conflicting with using this approach.

So I tried installing the [Bitnami Harbor Helm chart](https://github.com/bitnami/charts/tree/master/bitnami/harbor) which uses these same images on a K8s cluster, exposing it through a NGINX Ingress Controller:

```console
$ helm install harbor bitnami/harbor \
    --set service.type=Ingress \
    --set ingress.enabled=true \
    --set ingress.annotations."kubernetes\.io/ingress\.class"=nginx \
    --set externalURL=https://core.harbor.domain
```

I associated this domain to my NGINX Ingress Controller external IP:

```console
$ echo "$35.243.164.81 core.harbor.domain" | sudo tee -a /etc/hosts
```

I also had to add the registry to the list of insecure registries (since I didn't provide valid TLS certificates). You can do it editing the `/etc/docker/daemon.json` (Linux) or going to "Docker" -> "Preference" -> "Docker Engine" if you're on a MAC, see:

![Screenshot 2020-07-09 at 11 56 29](https://user-images.githubusercontent.com/6740773/87028425-e2c9d500-c1de-11ea-90ea-c084d7479337.png)

Finally, I obtained the credentials, and login:

```console
$ echo Credentials: "admin $(kubectl get secret --namespace default harbor-core-envvars -o jsonpath="{.data.HARBOR_ADMIN_PASSWORD}" | base64 --decode)"
Credentials: admin ARbo5nns4t
$ echo "ARbo5nns4t" | docker login --username admin --password-stdin https://core.harbor.domain
Login Succeeded
```

**Comment by skandragon** [comment]
@juan131 I'm not sure this issue and the one I listed (#7) are the same.  This one seems to require insecure repositories, but the one in #7 is using SSL to connect, a proper public IP address and domain name, with a trusted SSL certificate.

**Comment by skandragon** [comment]
From the logs, I see a GET to /v2/, which results in a Www-Authenticate header showing where to get a token.  This is the next call, and then once the token is granted, Docker tries to use it, which then fails.

**Comment by skandragon** [comment]
```
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 20786d78-33db-4a82-97ef-2aa91917f9d0 to the logger for the request GET /v2/
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/middleware/security/unauthorized.go:29][requestID="20786d78-33db-4a82-97ef-2aa91917f9d0"]: an unauthorized security context generated for request GET /v2/
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /v2/
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/error/error.go:58]: {"errors":[{"code":"UNAUTHORIZED","message":"unauthorized: unauthorized"}]}
nginx           | 68.97.160.145 - - [14/Jul/2020:02:19:26 +0000] "GET /v2/ HTTP/1.0" 401 76 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(darwin\x5C))"
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 96bd0379-7fa1-4c99-ac8c-a50a87ee1403 to the logger for the request GET /service/token
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/common/dao/user.go:277]: Check if user explorer is super user
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/core/auth/authenticator.go:139]: Current AUTH_MODE is db_auth
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/middleware/security/basic_auth.go:48][requestID="96bd0379-7fa1-4c99-ac8c-a50a87ee1403"]: a basic auth security context generated for request GET /service/token
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/core/service/token/token.go:35]: URL for token request: /service/token?account=explorer&client_id=docker&offline_token=true&service=harbor-registry
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/core/service/token/creator.go:203]: scopes: []
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/core/service/token/authutils.go:48]: scopes: []
nginx           | 68.97.160.145 - explorer [14/Jul/2020:02:19:26 +0000] "GET /service/token?account=explorer&client_id=docker&offline_token=true&service=harbor-registry HTTP/1.0" 200 1109 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(darwin\x5C))"
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id 9cd5700c-a3d9-4512-b71f-cab4c1c025db to the logger for the request GET /v2/
harbor-core     | 2020-07-14T02:19:26Z [DEBUG] [/server/middleware/artifactinfo/artifact_info.go:53]: In artifact info middleware, url: /v2/
registry_1      | time="2020-07-14T02:19:26.789874543Z" level=debug msg="authorizing request" go.version=go1.14.4 http.request.host=docker.flame.org http.request.id=7408a312-9d55-4f06-8114-336344def00f http.request.method=GET http.request.remoteaddr=68.97.160.145 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))"
registry_1      | 172.28.0.7 - - [14/Jul/2020:02:19:26 +0000] "GET /v2/ HTTP/1.1" 401 87 "" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \\(darwin\\))"
registry_1      | time="2020-07-14T02:19:26.789987918Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.14.4 http.request.host=docker.flame.org http.request.id=7408a312-9d55-4f06-8114-336344def00f http.request.method=GET http.request.remoteaddr=68.97.160.145 http.request.uri="/v2/" http.request.useragent="docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \(darwin\))"
nginx           | 68.97.160.145 - - [14/Jul/2020:02:19:26 +0000] "GET /v2/ HTTP/1.0" 401 87 "-" "docker/19.03.8 go/go1.12.17 git-commit/afacb8b kernel/4.19.76-linuxkit os/linux arch/amd64 UpstreamClient(Docker-Client/19.03.8 \x5C(darwin\x5C))"
```

**Comment by skandragon** [comment]
I also see some internal activity on port 5000 of the registry, where an authentication request with `harbor_registry_user:harbor_registry_password` is attempted, and rejected using the same `Www-Authenticate` header.  I do not see a second attempt, so whatever is making this request, returns the 401.

**Comment by skandragon** [comment]
So far, my debugging of this issue (I'm just trying harbor out as well) seems to be that when harbor-core sends an internal request to the registry on port 5000, it uses an auth of `harbor_registry_user:harbor_registry_password` to authenticate, and that is returning a request for a token handshake, which either fails or isn't started.

I could be wrong, but I think the flow is:

```
client -> nginx -> /v2/ with no auth.  harbor-core handles this, and returns 401 with the token URI.
client -> nginx -> token-uri, with basic auth.  harbor-core handles this, and returns a token.
client -> nginx -> /v2/ with token auth.  harbor-core accepts this, and forwards the request to harbor-registry, using the `harbor_registry_user:harbor_registry_password` credentials.  This is rejected by the registry with a token-uri 401 reply.
```
At this point, the world collapses and we're rejected.

**Comment by skandragon** [comment]
I now can log in.  I'm not sure if this is the "correct" way, and would be interested if this leads to a security issue.

I added this to the nginx.conf:

```
  upstream registry {
    server registry:5000;
  }
```

I then changed the /v2/ path to use:

```
    location /v2/ {
      proxy_pass http://registry/v2/;
```

Behavior:
* Docker login fails with an invalid password but a known user.
* Docker login works with a proper password and a known user.
* Docker push works if I'm logged in.
* Docker pull fails if I am not logged in.

**Comment by skandragon** [comment]
Further progress, using core (as it needs to be in the path for redis to be populated)

I reset the proxy back to the default config, with /v2/ going through core.

I modified registry/config.yml to contain:

```
auth:
  htpasswd:
    realm: basic-realm
    path: /etc/registry/htpasswd
```

I then set the user in htpasswd to contain `harbor_registry_user:harbor_registry_password` as a valid user.

Using this, I can push, pull, and images show up in the UI properly.

I do see this in logs:

```
harbor-core     | 2020-07-15T03:16:54Z [DEBUG] [/server/middleware/log/log.go:30]: attach request id d8e3629e-1630-498d-875d-785a2af627fe to the logger for the request POST /service/notifications
harbor-core     | 2020-07-15T03:16:54Z [DEBUG] [/server/middleware/security/unauthorized.go:29][requestID="d8e3629e-1630-498d-875d-785a2af627fe"]: an unauthorized security context generated for request POST /service/notifications
registry_1      | time="2020-07-15T03:16:54.09736027Z" level=error msg="retryingsink: error writing events: httpSink{http://core:8080/service/notifications}: response status 404 Not Found unaccepted, retrying"
registry_1      | time="2020-07-15T03:16:54.097379746Z" level=warning msg="httpSink{http://core:8080/service/notifications} encountered too many errors, backing off"
```

This error is repeated, apparently forever.

**Comment by juan131** [comment]
Hi @skandragon 

Thanks so much for the suggestion about the NGINX configuration. I just tried and it also works for me. These are my changes:

```diff
$ git diff
diff --git a/config/proxy/nginx.conf b/config/proxy/nginx.conf
index 833c54c..b2af699 100644
--- a/config/proxy/nginx.conf
+++ b/config/proxy/nginx.conf
@@ -22,6 +22,10 @@ http {
     server portal:8080;
   }

+  upstream registry {
+    server registry:5000;
+  }
+
   log_format timed_combined '$remote_addr - '
     '"$request" $status $body_bytes_sent '
     '"$http_referer" "$http_user_agent" '
@@ -99,7 +103,7 @@ http {
     }

     location /v2/ {
-      proxy_pass http://core/v2/;
+      proxy_pass http://registry/v2/;
       proxy_set_header Host $http_host;
       proxy_set_header X-Real-IP $remote_addr;
       proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

I added "reg.mydomain.com" to my `/etc/hosts`:

```console
$ echo "127.0.0.1 reg.mydomain.com" | sudo tee -a /etc/hosts
127.0.0.1 reg.mydomain.com
```

Then, I tested it:

```console
$ docker-compose up -d
$ echo "bitnami" | docker login --username admin --password-stdin http://reg.mydomain.com
Login Succeeded
```

I didn't need to modify the `registry/config.yml`

**Comment by siredmar** [comment]
Thanks for your insights! I also adapted your patch (from comment https://github.com/bitnami/bitnami-docker-harbor-portal/issues/4#issuecomment-658697024). 
It works now! Many thanks! Any chance this gets in an official bitnami release?

**Comment by juan131** [comment]
Yes!! Let's wait for @skandragon and @shrisidepocket to confirm it also works for them, and we can include these changes in the repo

**Comment by skandragon** [comment]
> Hi @skandragon
> 
> Thanks so much for the suggestion about the NGINX configuration. I just tried and it also works for me. These are my changes:
> I didn't need to modify the `registry/config.yml`

Note that this was a mistake on my part, and while it makes the registry itself work, the artifacts will not appear in the web UI.  The right thing to do is likely the htpasswd method, as that still routes through core and makes all the features we want Harbor for (over a simple docker registry)

**Comment by skandragon** [comment]
@juan131 I think the proper fix is this:

https://github.com/bitnami/bitnami-docker-harbor-portal/issues/4#issuecomment-658521927

The other fixes remove all the UI tracking of artifacts.

**Comment by skandragon** [comment]
I think there is another issue, that would have provided a hint if I had found this out.

There are two config directories in this repo. One works, one fails.  Use the first one.

https://github.com/bitnami/bitnami-docker-harbor-portal/tree/master/2/debian-10/config

https://github.com/bitnami/bitnami-docker-harbor-portal/tree/master/config

**Comment by juan131** [comment]
You're 100% right! I don't know how I could miss that... Sorry for the noise.
As you said, you should always try to use the files under the specific branch, since they're automatically updated when we include changes in our pipeline. That said, I just created a PR to update the "config" folder available at the repo's root.

**Comment by juan131** [comment]
I proceed to close this issue, but please feel free to reopen it if you continue having issues with docker login.
