### ISSUE TITLE
nginx.conf exposed

### ISSUE THREAD

**Issue by schnatterer** [bitnami/bitnami-docker-harbor-portal#5]
`https://${HARBOR}/nginx-conf/nginx.conf` is available via HTTP.

It's contained within the `bitnami/habor-portal` image at
`/opt/bitnami/harbor/nginx-conf/nginx.conf`.

**Steps to reproduce the issue:**

1. `helm install my-release --version 6.0.2 bitnami/harbor`
2. `kubectl service/my-release-harbor 8443:443`
3. `curl -k https://localhost:8443/nginx-conf/nginx.conf `

Or shorter:
`docker run --rm -it --entrypoint cat docker.io/bitnami/harbor-portal:2.0.0-debian-10-r11 /opt/bitnami/harbor/nginx-conf/nginx.conf`

**Describe the results you received:**

An NGINX conf is returned.

**Describe the results you expected:**

No NGINX conf externally available via HTTP

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by javsalgar** [comment]
Hi,

Thanks for letting us know. I was able to reproduce the issue. I'm working on a fix for it. I will update the ticket as soon as I have more news.

**Comment by javsalgar** [comment]
Hi,

In the latest release the issue is solved, now you should not be able to access the nginx conf file

https://github.com/bitnami/bitnami-docker-harbor-portal/commit/5a48ad72be73b4c1930ae54fa4a93bee1b8338ed

**Comment by schnatterer** [comment]
Thanks @javsalgar 
When I start `docker.io/bitnami/harbor-portal:2.0.0-debian-10-r13`, locally, `nginx-conf/nginx.conf` returns 404.
Thanks!
