### ISSUE TITLE
Incorrect time in http request

### ISSUE THREAD

**Issue by leonardoabenitez** [bitnami/bitnami-docker-harbor-portal#6]
Hi!

I am getting a response with the wrong time:

lbenitez@DGN-TECNO-06:~$ date
vie jun 26 09:54:58 -03 2020
lbenitez@DGN-TECNO-06:~$ sudo curl -i -k -u admin:bitnami http://192.168.20.24/service/token\?service\=harbor-registry
HTTP/1.1 200 OK
Server: nginx
Date: Fri, 26 Jun 2020 12:54:59 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 1105
Connection: keep-alive
Set-Cookie: sid=93a69dacc7631a39961423074a1f98d8; Path=/; HttpOnly
X-Request-Id: 662ec589-4fb6-4f41-87a0-e53abcf4e0da__

I have already mounted the volumes with their respective timezones and the instances show the correct date, but the answer is wrong (shown above). any suggestion? Could this be the reason the login fails? Thank you very much!!!

**Comment by miguelaeh** [comment]
Hi @leonardoabenitez ,
it seems that the timezone is not correct, I think it can be changed at the `harbor.cfg` file.

> Could this be the reason the login fails?

Also, could you elaborate on this? I can see you login correct from the response `HTTP/1.1 200 OK`

**Comment by leonardoabenitez** [comment]
Hi @miguelaeh,

I can't find the harbor.cfg file in these deployment steps, just find the docket-compose.yml and config inside of which are: clair core jobservice proxy registry registryctl. 

Although the answer is correct: 200, when I try to log in I get:
docker login 192.168.20.24
Username: admin
Password: 
Error response from daemon: login attempt to http://192.168.20.24/v2/ failed with status: 401 Unauthorized

Obviously from the web accesso I can enter correctly with those credentials

Thank you so much for everything

**Comment by miguelaeh** [comment]
Hi @leonardoabenitez ,
Could you share the logs of the containers after the login? Can you see any errors?
